### ISSUE TITLE
json_to_book method in Edition is not marked correctly

### ISSUE THREAD

**Issue by salman-bhai** [internetarchive/openlibrary-client#101]
```python
@classmethod
def json_to_book(cls):
     pass
```

Method for `Class Edition` in the file `openlibrary.py`

**Comment by mekarpeles** [comment]
I think we can probably remove this stub! deprecated

**Comment by Oisins** [comment]
Hi,
I created a pull request that removes this method. One consideration might be it's usage in other peoples code, but since it only runs `pass` I think it should be ok. Thank you for marking this as hacktoberfest and encouraging me to contribute to projects like this!
