### ISSUE TITLE
Preventing Author Creation if "," in name

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary-client#103]
We want to enforce "natural sort order" for our author names (meaning *not* last, first)

We'll want to:
1) create a news type of Exception called e.g. `SuspiciousAuthorFormatException` for author names containing `,` in them
2) Update the Author class (and possible the add_book method) to check author name before creating a new book on openlibrary.org
3) add a test to `openlibrary-client` to verify that a `SuspiciousAuthorFormatException` is raised when a user attempts to create an author w/ a `,` in the name

**Comment by LeadSongDog** [comment]
Create? Why not just import?

**Comment by tfmorris** [comment]
Creating technical enforcement mechanisms is useful, but until they exist we should use conventions to make sure the rules are followed. This author linked to from the GSoC blog post was just created a couple of months ago in the wrong format https://openlibrary.org/authors/OL7416671A/Eagle_Audrey_Lily

**Comment by tfmorris** [comment]
We want to discourage people from doing bad things like Last, First or Author1, Author2 and Author3, but is an outright ban on commas the way to do it? Are there no valid uses for commas in an author record? Whatever validity check is decided on, it should go server-side, not client side where it only affects users of one tool.
