### ISSUE TITLE
Don't save cleartext passwords

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary-client#12]
The README says:

> This process will ask for a username and password and save them in ~/.config/ol.ini (or whichever config location the user has specified). In the next version, the password will not be stored; instead the account will be authenticated and the username and resulting cookie (and not the password) will be stored in the config

This is a security risk, so I think it's time for "the next version."

**Comment by mekarpeles** [comment]
To be addressed by #31 (in CR). cc: @tfmorris, @cdrini, @hornc
