### ISSUE TITLE
MARC 'unicode'? 

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#122]
This check / transform looked wrong to me:

https://github.com/internetarchive/openlibrary-client/blob/e7920d9e82b62711f47db4f941c2ca266764c2a4/olclient/marc.py#L188-L189

Not sure what it is trying to do, but raw MARC is a binary format, not "unicode". Characters in a MARC file can be utf-8 or MARC8 encoded. 

Maybe it is doing the correct thing, but is confusingly named?

```
>>> isinstance(b"a\x1fb", bytes) # is untouched because it is already type=bytes
True
>>> isinstance(u"a\x1fb", bytes)
False
>>> isinstance(u"a\x1fb", unicode)
True
 isinstance(u"a\x1fb".encode("utf-8"), bytes)
True
```

So if `marc` is type=unicode, it is converted into type=bytes and stored in `unicode_marc`

`unicode_marc` is always type=bytes

This actually seems the correct behaviour to me, but the variable name is :confused:

**Comment by cclauss** [comment]
That test only works on legacy Python.

**Comment by cclauss** [comment]
Is this issue clearer now with all your recent work on marc?

**Comment by cclauss** [comment]
@hornc Has this been deal with?

**Comment by hornc** [comment]
No. I don't know if anyone is using this tool to process MARC records, or if this code has ever worked.

My opinion is this feature should be removed since the Open Library API has a MARC ingestion endpoint already at /api/import which correctly handles the various fields and identifiers.

If this is removed, there is also an issue to remove the dependency on yaz command line tools which can be dealt with too.
