### ISSUE TITLE
T-Shirt author: https://openlibrary.org/authors/OL3832914A/Xlarge

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#124]
Non book items need removing

**Comment by tfmorris** [comment]
Is this a bug in the client code or just a data issue on the Open Library web site that needs to be fixed there?

**Comment by BharatKalluri** [comment]
The author along with corresponding editions and works have been deleted deleted using a google colab notebook, after having a chat with Lisa 🎉 
I think we can close this issue now. 

cc @cdrini

**Comment by cdrini** [comment]
Awesome! Thanks @BharatKalluri !
