### ISSUE TITLE
Some works with unknown authors have an `authors` value with only a `type`

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#126]
The correct way to represent an unknown author (which is a valid for a work) is to have no `authors` value at all.

command to identify all works with this problem from the DB dumps:

`grep -c '"authors": \[{"type": {"key": "/type/author_role"}}\]' ol_dump_works_2018-12-31.txt`
=> 31532

**Tasks:** 
- [ ] Check the UI save function is not adding the `type` to empty authors fields as described in #44
- [ ] Remove the `authors` value completely from these works using a script.

**Comment by hornc** [comment]
`grep -c '"authors": \[{"type": {"key": "/type/author_role"}}\]' /storage/openlibrary/ol_dump_works_2019-01-31.txt `
=> 31834

This number has ''increased'' which is worrying - will investigate further.

**Comment by tfmorris** [comment]
Seems like it would be straightforward to generate a list of the new broken entries, which might make it easy to identify a pattern...

**Comment by tfmorris** [comment]
Increased another 4K in 7 months. Clearly some piece of code is still creating these entries.

```
$ time zgrep -c '"authors": \[{"type": {"key": "/type/author_role"}}\]' ol_dump_2019-08-31.txt.gz 
35686
```

**Comment by tfmorris** [comment]
Here are the first couple of dozen from 2019. My extremely scientific sampling of the first 5 indicates that they were all added by users through the web UI, so I'm guessing that's where the bug is.

```
$ zgrep  '"authors": \[{"type": {"key": "/type/author_role"}}\]' ol_dump_2019-08-31.txt.gz | grep 2019 | cut -f 5 | jq -r . | grep key | grep works | cut -f 4 -d '"'
/works/OL16194414W
/works/OL18186774W
/works/OL18187368W
/works/OL19325330W
/works/OL19339973W
/works/OL19638832W
/works/OL19647214W
/works/OL19650838W
/works/OL19654944W
/works/OL19658544W
/works/OL19701934W
/works/OL19702074W
/works/OL19797681W
/works/OL19823166W
/works/OL19830184W
/works/OL19916226W
/works/OL19916420W
/works/OL20065043W
/works/OL20081540W
/works/OL20087047W
/works/OL20114659W
/works/OL18188502W
/works/OL18203667W
/works/OL19084144W
/works/OL19085019W
/works/OL19085657W
```

**Comment by LeadSongDog** [comment]
Well the first of those is 8 years old gibberish, not new this year. I haven’t checked the others.

**Comment by hornc** [comment]
These no-author works appear to all be user created without authors.  I think @tfmorris is correct with the #6565 link.

Here are some of the most recent works with this invalid empty author format:

```
OL21115756W	2020-08-04T21:47:16.104454
OL21348733W	2020-08-17T22:06:21.418232
OL21392869W	2020-08-19T16:06:37.858237
OL21616248W	2020-08-25T02:52:55.284580
OL22659571W	2020-10-19T08:13:23.017102
OL22661772W	2020-10-19T14:57:38.355978
OL22662607W	2020-10-19T20:02:39.735816
OL22709948W	2020-10-27T19:50:27.495750
OL22992858W	2020-11-05T19:16:50.311106
OL23175010W	2020-11-12T17:17:43.339286
OL24142386W	2021-01-07T19:49:20.038230
OL24167837W	2021-01-27T10:11:52.876583
OL24181575W	2021-02-04T13:53:04.131226
OL24468748W	2021-05-13T14:18:39.135921
OL24545479W	2021-05-29T23:52:38.999182
OL24550916W	2021-05-31T08:40:41.194798
OL24553258W	2021-05-31T20:02:22.145195
OL24559089W	2021-06-02T20:10:39.721287
OL24559111W	2021-06-02T20:19:44.030662
OL24583590W	2021-06-09T18:18:45.913015
OL24702784W	2021-07-13T11:10:53.447014
OL24756869W	2021-07-25T20:04:14.518529
OL26751687W	2021-12-29T13:58:51.495679
OL27038451W	2022-01-11T19:07:32.978494
OL27307978W	2022-02-21T16:17:48.615072
OL27710820W	2022-04-06T09:33:40.278811
OL28606475W	2022-08-13T18:20:35.934217
OL28758109W	2022-08-19T13:04:58.804063
OL28772784W	2022-09-12T13:33:10.979154
OL29230716W	2022-10-20T12:26:48.945580
```

The /books/add endpoint must be creating these. Locating the code where the work is created for the /books/add UI and ensuring no author key is added if the author is not provided seems like the fix.

**Comment by hornc** [comment]
Creating a new book with no author creates a work with `authors = []` (different from this issue). https://openlibrary.org/works/OL34308848W.json?v=1

Saving it again on the edit interface clears the empty list: https://openlibrary.org/works/OL34308848W.json?v=2

I can't see any `"authors": []` in the ol_dump_works_2023-01-10.txt.gz work dump

    zgrep '"authors": \[\]' ol_dump_works_2023-01-10.txt.gz

This makes me think that this is an historical issue (fixed semi-recently, possibly by changes around this: https://github.com/internetarchive/openlibrary/pull/6979/commits/89e4b4431fe7506c365a6f6eb6f6d048d04c044c ? )

Only data clean up left.

**Comment by hornc** [comment]
This is still an ongoing problem, but the root cause is covered by https://github.com/internetarchive/openlibrary/issues/6565
