### ISSUE TITLE
Use less restrictive license for client code

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary-client#13]
It's a pretty common practice to follow different license strategies for server and client code with client libraries, example code, etc being permissively licensed to encourage their use in applications.

I'd like to suggest that this client library be switched to a BSD license.

**Comment by mekarpeles** [comment]
@tfmorris, I can float the idea up the chain; I am currently stuck w/ agpl3 as this is the preferred license for projects under `internetarchive`. It's also what the `internetarchive` tool uses: https://github.com/jjjake/internetarchive/blob/master/LICENSE

**Comment by tfmorris** [comment]
Thanks for fighting for the switch. Sorry you weren't successful. 

I'll see if I can find time to start an implementation of a client library which is freely available for everyone to use. Unfortunately, that'll probably mean less/no time to contribute to this library.
