### ISSUE TITLE
Wiki needs update

### ISSUE THREAD

**Issue by rahul-kumi** [internetarchive/openlibrary-client#130]
- The following code snippet under the `Work` section of the [wiki](https://github.com/internetarchive/openlibrary-client/wiki/Work) is not currently supported hence needs to be removed(or replaced).
> **4. Search for a work via Author or Title**
> 
> Get the closest matching result in OpenLibrary based on a title and author.
> ```
> >>> from olclient.openlibrary import OpenLibrary
> >>> ol = OpenLibrary()
> >>> ol.get_book_by_metadata(title=u'The Autobiography of Benjamin Franklin')
> 
> or
> 
> >>> from olclient.openlibrary import OpenLibrary
> >>> ol = OpenLibrary()
> >>> ol.get_book_by_metadata(author=u'Dan Brown')
> ```

- Additional code samples have to be included in the wiki, demonstrating openlibrary-client's complete set of supported functionalities.

**Comment by mekarpeles** [comment]
resolved, thank you!
