### ISSUE TITLE
Incorrect language field format on many records

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#135]
There are at least two incorrect language fomats on editions:

`"language": "eng"`

and

`"language": [{"key": "/languages/eng"}]`

The **CORRECT** field name is `languages`, and the format is `[{"key": "/languages/eng"}]`

A bot clean task would be to find and correct all the wrong language forms so they show up correctly in the UI and are searchable etc

**Comment by guyjeangilles** [comment]
Inspecting the June 2020 dump finds 3M+ editions that don't conform to this schema
```bash
$ zgrep ^/type/edition ../ol_dump_2020-06-30.txt.gz | grep -v '"languages": \[{"key": "/languages' | pv | gzip > malformed_language_editions.txt.gz
$ zcat malformed_language_editions.txt.gz | wc -l
3816911

```

**Comment by xayhewalo** [comment]
Revisiting this and better filtering finds 3,803 editions that actually contain the language data albeit malformed. A representative example: https://openlibrary.org/books/OL20434581M.json

Is there another source for the language code?
```
$ pv ol_dump_editions_2022-11-30.txt.gz  | zgrep '"language":\|"languages":' | grep -v '"languages": \[{"key": "/languages' | gzip > malformed_language_editions.txt.gz
7.81GiB 0:03:04 [43.3MiB/s] [===============================================>] 100%
$ wc -l malformed_language_editions.txt.gz 
3803 malformed_language_editions.txt.gz
```

**Comment by xayhewalo** [comment]
@tfmorris Do you have a representative example of the one letter prefix IDs? I tried searching the dump and didn't find a matching record. Also the JSON of the IDs above look well-formed.

Either way, the original problem with the language field feels like a bot job.

**Comment by tfmorris** [comment]
@xayhewalo I was using the 2021-11 dump for my initial development and when I switched to the 2022-11 dump for my final title language analysis, I didn't notice that 1-letter prefix issue was gone. Sorry! Looks like it was fixed some time in the last year.

**Comment by hornc** [comment]
OL26689927M has `"language": "engcze"` which is another incorrect example which should be fixed.

**Comment by LeadSongDog** [comment]
@hornc that edition is attributed to a redundant author record and so had a redundant work record linked. Once the authors are merged, the works can be merged too.  We don’t seem to have the original Czech rhyme/folksong "Šel jsem na trh" but only the English translation, so the reteller got “author” credit, notwithstanding what was on the cover image!

**Comment by tfmorris** [comment]
@hornc Should this be moved to the @openlibrary repository? As I mentioned before, it seems like a data quality issue and not one which needs an aggressively licensed AGPL library to fix.

But to continue the thread, for wherever it gets moved, there are also examples with the language name written out. Here's a summary of the cases with the values for the `language` key and the `languages` key:

```
2813 [{"key":"/languages/eng"}]	- move array from `language` to `languages`
2150 "eng"	- create `languages` [{"key":"/languages/eng"}]
 506[{"key":"/languages/fre"}]	- move
 457 [{"key":"/languages/ger"}]	
   81 "English"	- create `languages` [{"key":"/languages/eng"}]
  79 [{"key":"/languages/spa"}] 
  79 [{"key":"/languages/ita"}] 
  59 [{"key":"/languages/lat"}] 
  42 [{"key":"/languages/eng"}] [{"key":"/languages/eng"}] - delete redundant `language`
  34 "eng"	[{"key":"/languages/eng"}] - delete redundant `language`
  23 "French"	create `languages` [{"key":"/languages/fre"}]
  20 [{"key":"/languages/rus"}] 
  17 [{"key":"/languages/dut"}] 
  15 [{"key":"/languages/dan"}] 
  15 "German"   
   7 "fre"      
...
   6 "engfre"   - split & create `languages` [{"key":"/languages/eng"},{"key":"/languages/fre"}]
...
   1 "engfregeritaspa"	- split & create `languages` for all 5 languages
...
   1 "eng"	[{"key":"/languages/spa"}] - ??? conflict ??? review by hand
   1 "[electronic resource] /"  [{"key":"/languages/eng"}]
...
   1 "English." 
```

My analysis turned up a total of 68 different sets of bad values, across 6-7K records, but they all fall into the handful of categories outlined above.

**Comment by xayhewalo** [comment]
I started a branch to address this issue: https://github.com/xayhewalo/openlibrary-bots/blob/language_bot/languagebot/fix_language_attribute.py. I won't claim the code is amazing but it should fix most existing records. It won't address the systematic issues Tom referenced.

A sample log of the changes the current code makes.

```
jobs.olclient.bots;INFO    ;2023-01-19 17:16:14,920 OL20614128M 'language': [{'key': '/languages/eng'}]    'languages:' [{'key': '/languages/eng'}]
jobs.olclient.bots;INFO    ;2023-01-19 17:16:15,459 OL26638699M 'language': 'eng'    'languages:' ['eng', {'key': '/languages/eng'}]
```

**Comment by hornc** [comment]
This looks like it is almost resolved, only ~35 incorrect `language` keys in the ol_dump_editions_2023-08-31.txt.gz dump:

- [ ] https://openlibrary.org/books/OL26640245M
- [ ] https://openlibrary.org/books/OL20432173M
- [ ] https://openlibrary.org/books/OL26647321M
- [ ] https://openlibrary.org/books/OL26616090M
- [ ] https://openlibrary.org/books/OL20544371M
- [ ] https://openlibrary.org/books/OL20474664M
- [ ] https://openlibrary.org/books/OL20624361M
- [ ] https://openlibrary.org/books/OL20515836M
- [ ] https://openlibrary.org/books/OL20584145M
- [ ] https://openlibrary.org/books/OL20616786M
- [ ] https://openlibrary.org/books/OL20486367M
- [ ] https://openlibrary.org/books/OL20470953M
- [ ] https://openlibrary.org/books/OL26618945M
- [ ] https://openlibrary.org/books/OL20547571M
- [ ] https://openlibrary.org/books/OL20556315M
- [ ] https://openlibrary.org/books/OL26619613M
- [ ] https://openlibrary.org/books/OL20609289M
- [ ] https://openlibrary.org/books/OL20547517M
- [ ] https://openlibrary.org/books/OL26640159M
- [ ] https://openlibrary.org/books/OL20542661M
- [ ] https://openlibrary.org/books/OL26617926M
- [ ] https://openlibrary.org/books/OL20550784M
- [ ] https://openlibrary.org/books/OL26615538M
- [ ] https://openlibrary.org/books/OL26639999M
- [ ] https://openlibrary.org/books/OL20441274M
- [ ] https://openlibrary.org/books/OL20609591M
- [ ] https://openlibrary.org/books/OL20447816M
- [ ] https://openlibrary.org/books/OL26648016M
- [ ] https://openlibrary.org/books/OL20617222M
- [ ] https://openlibrary.org/books/OL20539021M
- [ ] https://openlibrary.org/books/OL26647298M
- [ ] https://openlibrary.org/books/OL20622768M
- [ ] https://openlibrary.org/books/OL26618030M
- [ ] https://openlibrary.org/books/OL20587477M
- [ ] https://openlibrary.org/books/OL20554136M

**Comment by hornc** [comment]
all fixed
