### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary-client#14]
The assumption that things written for Python 2.7 will work on Python 3.x turns out to be untrue (and, philosophically, some would say that anything that's not covered by tests can be assumed to not work).

**Comment by mekarpeles** [comment]
We'll likely have to bite the bullet at some point and move from web.py + infogami to something like flask towards this goal.

**Comment by mekarpeles** [comment]
Ignore my previous comment as I read it as being `openlibrary` not `openlibrary-client`

Agreed, Python3 support is a great near-term goal
