### ISSUE TITLE
I keep recieving "Incorrect credentials..." although have entered correct credentials

### ISSUE THREAD

**Issue by codingforpleasure** [internetarchive/openlibrary-client#145]
I have installed the openlibrary-client package on my **ubuntu**,
and mde sure my archive.org account works properly (been able to log into my account easily),
but as I configure the ol client i keep getting after few seconds:

**"Incorrect credentials, not updating config."**

I noticed the ia.ini is getting generated correctly since my screenname field which was retrieved from archive.org is indeed correct, but the ol.ini remains empty. how come?
Does anybody know how to resolve this issue?

Thank you

**Comment by codingforpleasure** [comment]
My mistake, it  works well!

**Comment by kassimorra** [comment]
hey, do you made any changes to make it work ? 

I'm having this same issue, but i'm pretty sure about my password.

Do you know if there is a restriction about special character ?
