### ISSUE TITLE
Remove requirement for shell utilities (ie yaz)

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary-client#15]
It's both kludgy and non-portable, so it'd be better if there were a Python solution (I'll research alternatives).

**Comment by tfmorris** [comment]
The utility is available for Macports, 32 & 64 bit Windows, as well as multiple Linux distributions, so the portability impact may be minimal. It'd still be nice to eliminate the dependency though, since only a tiny bit of functionality is used.

**Comment by hornc** [comment]
Yaz-marcdump is only used to convert the "line format" MARC records e.g. https://github.com/internetarchive/openlibrary-client/blob/e7920d9e82b62711f47db4f941c2ca266764c2a4/examples/marc/line_marc.txt  to binary MARC, which is then processed like the rest of the MARC data using the python module `pymarc`

`convert()` is here https://github.com/internetarchive/openlibrary-client/blob/e7920d9e82b62711f47db4f941c2ca266764c2a4/olclient/marc.py#L177

and it is only called from
`line_to_book()` https://github.com/internetarchive/openlibrary-client/blob/e7920d9e82b62711f47db4f941c2ca266764c2a4/olclient/marc.py#L198
and 
`line_to_dict()` https://github.com/internetarchive/openlibrary-client/blob/e7920d9e82b62711f47db4f941c2ca266764c2a4/olclient/marc.py#L141

If we found another way of handling "line format" MARC, or deprecated it entirely, we could remove the Yaz-marcdump cli dependency.
