### ISSUE TITLE
Set up CI server

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary-client#17]
A continuous integration server such as Travis CI would be a very useful bit of infrastructure (and free).

**Comment by tfmorris** [comment]
I think the Travis setup is in pretty good shape now. We just need it enabled.

**Comment by mekarpeles** [comment]
Thanks @tfmorris, should we close this for now or are there any components still needed?

**Comment by tfmorris** [comment]
LGTM. I've got a separate PR coming with the build badge and updates to the Python versions for the ReadMe, but it's not critical
