### ISSUE TITLE
Release final Python2 release

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary-client#192]
We're dropping python2 support, and would like to release the last py2 master ( e51de13 ) as the last python2 version. Last release was in February.

**Comment by cclauss** [comment]
What is the process for [releasing to PyPI](https://pypi.org/project/openlibrary-client/)?  Repos such as openlibrary-bots can no longer build because of pip conflict resolution errors.

**Comment by hornc** [comment]
@cclauss I don't have access to push to pypi, I believe @mekarpeles does?
