### ISSUE TITLE
Add EDIT functionality to openlibrary-client

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary-client#2]
Port over the EDIT functionality of https://github.com/internetarchive/openlibrary/blob/master/openlibrary/api.py (which allows one to edit the metadata of Editions, Works, etc) into the openlibrary-client

**Comment by mekarpeles** [comment]
This includes the ability to .save() an object (such as an Author) by having it convert/marshal the openlibrary-client data structure to the json schema expected by the endpoint. Ultimately this save() will result in a PUT of this marshaled json data.

**Comment by mekarpeles** [comment]
@hornc would benefit from this feature -- currently, he is using this workaround to (e.g.) add VIAF and wikidata remote_ids to Authors: https://gist.github.com/hornc/36a6cadb4aa0a7c6eee4272bd15a5b68

**Comment by hornc** [comment]
Here are two simple methods to save one OL json formatted 'thing' (work / edition / author), and many things at once:

```
    def save_one(self, doc, comment):
        doc['_comment'] = comment
        return self.session.put(self.base_url + doc['key'] + ".json", json.dumps(doc))
```

```
    def save_many(self, docs, comment):
        headers = {
            'Opt': '"http://openlibrary.org/dev/docs/api"; ns=42',
            '42-comment': comment
        }
        return self.session.post(self.base_url+'/api/save_many', json.dumps(docs), headers=headers)
```

Putting them here for inclusion.

**Comment by hornc** [comment]
```
from olclient.openlibrary import OpenLibrary
ol = OpenLibrary()

work = ol.Work.get(u'OL12938932W')
editions = work.editions
```
## Proposed new methods to give write/edit ability to ol-client:
This functionality is present in my bot, I will just need to implement the JSON serialisation, (using `jsonpickle`?) and move the methods over to the corresponding classes.

### returns OL ready json representation of the entity:
`work.json()`

### coverts the entity into a delete object, DOES NOT save the delete
`work.delete()`

### converts the entity into a redirect object (check for same type), DOES NOT save
`work.redirect(destination_olid)` 

### writes the entity back to OL
`work.save(comment)`

### saves a list of OpenLibrary entities in one operation to OL
`ol.save_many([list of entities of class ol.Author | ol.Work | ol.Edition], comment)`

**Comment by mekarpeles** [comment]
Seems like we're headed in a productive direction. Wonderful job spec'ing this out.

## Feedback + questions for consideration:

re: jsonpickle, we may want to make sure dates are marshaled correctly (this is something which oftens goes awry w/ json en/de-coding

When one creates a work.redirect(...) -- which doesn't save -- I'm imagining this returns a json blob and not an object? Does one use something like an ol.save(blob)? Or does it update the `openlibrary-client` object w/ the necessary fields to mark it as a redirect. I actually like the idea of setting such things (e.g. redirect) on the object... Or having work.redirect be a special form of save, which has `dry_run=True` set by default.

Maybe we could/should have a kwarg `dry_run=True` by default which shows what the json would look like, without doing the save.

It would be nice if we had a method, e.g. `canonicalize` which any `thing` type (e.g. `work`, `edition`, `author`) class can implement (called by `save`) which would contain the gotchas and sanitization (i.e. "rules") we decide upon + update via regression tests.

Also, we may want to add something like a `_date_fetched` field to `openlibrary-client` objects and check within `save` if a save has been performed after fetch (and raise error) to prevent collisions.

**Comment by mekarpeles** [comment]
@hornc are we OK to close this issue for now? I believe we're still implementing edit functionality, but in the meantime saving() should work, right? Closing in anticipation. Feel free to re-open if I'm wrong.
