### ISSUE TITLE
Can not delete more than 50 records at a time

### ISSUE THREAD

**Issue by xayhewalo** [internetarchive/openlibrary-client#209]
As discussed in this week's call, deleting is a big part of librarian tasks and deleting >50 records at time will help our librarians.

**Comment by cclauss** [comment]
On what screen or in what file should this change be made?

**Comment by BharatKalluri** [comment]
Support for deleting in bulk was added @ https://github.com/internetarchive/openlibrary-client/pull/233 , I think we can close this issue.

(Colab link where `delete_many` was used: https://colab.research.google.com/drive/1bLbWs6YlvxXuP0Q--N6Os83ZmNLn0i8m?usp=sharing)
