### ISSUE TITLE
AbstractBotJob ignoring limit argument

### ISSUE THREAD

**Issue by jimman2003** [internetarchive/openlibrary-client#237]
Testing my bot https://github.com/internetarchive/openlibrary-bots/pull/108, I found out that setting the limit , does nothing (even with dry_run)..
It always runs with limit as default (1)...

**Comment by BharatKalluri** [comment]
Hi @jimman2003 , limit is an variable on the `AbstractBotJob`, which means that you can use `self.limit` variable inside your bot and use that to stop the execution of the for loop based on the limit.

Looks like the [making_a_bot.py](https://github.com/internetarchive/openlibrary-client/blob/master/examples/scripts/making_a_bot.py) is not using it. We could add limit usage there, i'll create a PR for that. 👍🏽

**Comment by jimman2003** [comment]
That is a workaround...We should imo fix the argument parsing in that class

**Comment by BharatKalluri** [comment]
@jimman2003 Yep, you're right. Looks like the definition of the flag was incorrect in the codebase. Fixed and made a PR. Thanks for the report!
