### ISSUE TITLE
Json schema is different

### ISSUE THREAD

**Issue by arkadybag** [internetarchive/openlibrary-client#259]
Hi guys, I just found that **[JSON SCHEMA](https://github.com/internetarchive/openlibrary-client/tree/master/olclient/schemata)** looks different for [work](https://openlibrary.org/type/work), [author](https://openlibrary.org/type/author) and [edition](https://openlibrary.org/type/edition)

It something strange happened, because in the repository the last commit in 2020, but for example, in author last change was in 2009, but json schema isn't good with it.

Is it fine that it different or what?

**Comment by hornc** [comment]
Closing as addressed.
