### ISSUE TITLE
Flavicon is missing

### ISSUE THREAD

**Issue by dunewtf** [internetarchive/openlibrary-client#267]
Flavicon (in header) is missing at some places. For example at the videoplayer after clicking on download (it will redirect to this:): [https://ia601305.us.archive.org/22/items/DuneTheCompleteSagaVimeo/Dune%20-%20The%20Complete%20Saga_vimeo_54644338.mp4](url)

**Comment by seabelis** [comment]
Not related to Open Library Client. Please close.
