### ISSUE TITLE
If server responds with 503 on get(olid), edition is silently assigned to None

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#29]
```
edition = ol.get(u'OL17922113M')
```
if the server responds with a 503 (or presumably other error codes?)
`edition` is `None` without any error or notification that something has gone wrong.

**Comment by mekarpeles** [comment]
This should probably `raise`

**Comment by tfmorris** [comment]
I think 5xx's should first be retried and only raise after the retry count is exceeded.

They *certainly* should result in corrupted data.

**Comment by hornc** [comment]
similar to #60

**Comment by hornc** [comment]
Fixed by #106
