### ISSUE TITLE
Document translation related edition fields in schema

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#342]
OL edition schema:

```
"translation_of": "Ai margini del caos"

"translated_from": [{"key": "/languages/ger"}]

"languages": [{"key": "/languages/fre"}]


```

The import schema will have:

    "translated_from": ["ger"]

in the same way it currently has 

    "languages": ["fre"]

https://github.com/internetarchive/openlibrary-client/blob/76a8700d6607b30a4c07f68196763f96c2cffa86/olclient/schemata/import.schema.json#L36-L39

and the shared def:

https://github.com/internetarchive/openlibrary-client/blob/76a8700d6607b30a4c07f68196763f96c2cffa86/olclient/schemata/shared_definitions.json#L33-L38

This relates to Open Library PR : https://github.com/internetarchive/openlibrary/pull/7407

See also: #135

**Comment by cclauss** [comment]
Side comment `Ai margini del caos` is not French.
