### ISSUE TITLE
Some authors have 'comment' property in their data

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#55]
12142 authors have a `comment` property in their data. The examples I have seen have value = "initial import"

```
grep -c '"comment":' /storage/openlibrary/ol_dump_authors_2017-09-30.txt 
12142
```

**Comment by cdrini** [comment]
Fixed; see edits starting from https://openlibrary.org/recentchanges/2018/07/31/bulk_update/54080849
