### ISSUE TITLE
ol.get() to raise an error when item is not found

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-client#60]
Currently not found authors and works returns an object:
```
>>> ol.get('OLnotA')
<class 'olclient.openlibrary.Author' {'bio': None, 'identifiers': {}, 'name': u'', 'olid': u'OLnotA', 'error': u'notfound'}>
```
```
>>> ol.get('OLnotW')
<class 'olclient.openlibrary.Work' {'_editions': [], 'key': u'/works/OLnotW', 'olid': 'OLnotW', 'error': u'notfound'}>
```

While a not found Edition returns `None`:

I suggest it should raise a "Not found" exception of some sort.

Similar to https://github.com/internetarchive/openlibrary-client/issues/29

**Comment by mekarpeles** [comment]
Yeah, absolutely shouldn't return a /works/OLnotW entry. We might even want to enforce a regex check to catch malformed olids separately.

**Comment by mekarpeles** [comment]
@hornc is this resolved by one of your recent PRs?

**Comment by hornc** [comment]
@mekarpeles afraid not, this is still an issue.

**Comment by hornc** [comment]
See https://openlibrary.org/books/OL25942179M/Books_of_imagination_Methodology_for_school_projects_My_dream_for_book_and_Alternative_bodies_of_the?b=11&a=10&_compare=Compare&m=diff 

for what can happen when a bot requests a OLID that doesn't exist and re-writes.
