### ISSUE TITLE
Create Book Ingestion Pipeline

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary-client#65]
It would be great if openlibrary-client could easily be extended to import new book metadata records from 3rd party partners (like BetterWorldBooks APIs, Onix Feeds, MARCs)

A good first step would be a small utility which can take an ISBN and lookup/pull information from other sources. This would be very helpful supplement for Openlibrary.org's "add a book" feature.

**Comment by CodeWolf1** [comment]
We could use this,
&bibkeys=ISBN:

**Comment by hornc** [comment]
Closing per internetarchive/openlibrary#688 -- this is more of an Open Library repo feature and ongoing concern. It's not clear what the action is for this _client_ repo.
