### ISSUE TITLE
Delete all Alice Kirk / BookBoon spam

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary-client#68]
https://openlibrary.org/people/AliceKirk
I came across this during the author merge cleanup because Alice created dozens of duplicate author records for the same person. 

Originally I thought this and the repetition in books e.g.
https://openlibrary.org/search?q=title%3A+%22Innovative+Design+Guidebook+for+Game+Changers%22&mode=everything

were just innocent mistakes, but after looking a little further I realized all the entries are just designed to turn OpenLibrary into a giant link farm for BookBoon.

In some cases, records were actively vandalized, like these two where works were retitled and reauthored: 

- https://openlibrary.org/works/OL2994057W/Long-Term_Assets?b=5&a=2&_compare=Compare&m=diff
- https://openlibrary.org/works/OL6830628W/Careering_Ahead?b=4&a=2&_compare=Compare&m=diff
 

Originally posted by @tfmorris: https://github.com/internetarchive/openlibrary/issues/711

**Comment by tfmorris** [comment]
Moving back to the original repo where I've reopened the original issue.

@mekarpeles Please close. I don't seem to have privs to do it.

**Comment by mekarpeles** [comment]
Ack, sorry, didn't intend to create this on olclient
