### ISSUE TITLE
Failed Author Merges to Fix

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary-client#72]
The merges from 2013 need to be undone. They've conflated a novelist with a statistician and affected thousands of works.

https://openlibrary.org/authors/OL24370A/Kathleen_Morgan

@leadsongdog writes:
The statistician is https://viaf.org/viaf/73431623
The pulp romance author is https://viaf.org/viaf/9176228

This issue originally opened here by @tfmorris:
https://github.com/internetarchive/openlibrary/issues/712

**Comment by hornc** [comment]
This looks to be the merge details: https://openlibrary.org/recentchanges/2013/07/09/merge-authors/47603340 

I am adding VIAF and ISNI to the authors and will attempt the revert...

**Comment by hornc** [comment]
I think I have reverted correctly, and corrected the authors' details: https://openlibrary.org/recentchanges/2018/04/09/undo/53724316

Solr may need some help getting updated, but I'll wait a while and give it a chance to update itself.

**Comment by hornc** [comment]
looks like solr updated and the works are showing correctly under the two authors:

https://openlibrary.org/authors/OL2812675A/Kathleen_O'Leary_Morgan
and
https://openlibrary.org/authors/OL24370A/Kathleen_Morgan

There are some exceptions, but those are orphaned editions, which solr has trouble removing. Separate issue though: https://github.com/internetarchive/openlibrary/issues/893
