### ISSUE TITLE
Delete 58k bad author names (CD catalog IDs)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary-client#73]
Delete ~55K bad author records with names matching the regex grep -E " Cd[a-zA-Z0-9]{2,4} " and related music CDs (ie 58565 less the 3415 that @hornc already deleted)
cc: @tfmorris, @mikemaehr, @bencomp, @hornc

Moved from https://github.com/internetarchive/openlibrary/issues/152#issuecomment-372927856

**Comment by tfmorris** [comment]
The bulk of the cleanup has been done already and number is down to 140 according to https://github.com/internetarchive/openlibrary/issues/152#issuecomment-373170438 so I'd consider this low priority.

**Comment by LeadSongDog** [comment]
There's a similar issue with cassettes, but "Cs" vice "Cd". Should that extend this issue, or be a new one? A subset: https://openlibrary.org/search/authors?q=+css*&mode=everything

**Comment by mekarpeles** [comment]
@LeadSongDog please do create a new issue on for "Cs", thank you!

**Comment by hornc** [comment]
Even though most of these 'Cd' authors have been deleted they still appear in solr search results. I am planning to create a bot that takes a OL Author search query and manually adds deleted authors that appear to manually re-index (now that a deleted authors solr bug is fixed)

**Comment by hornc** [comment]
I'm going to call this done. There are still some of these deleted authors not removed from Solr, but that it is a wider problem that needs to be addressed separately.
Tagging @tfmorris who was looking into generating lists of deleted items.

**Comment by tfmorris** [comment]
Sorry! I've got the lists. I'll get them uploaded to a new ticket.

**Comment by tfmorris** [comment]
I've created issue #78 for updating Solr based on the list of deleted authors.
