### ISSUE TITLE
Revive NYT bestseller bot?

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary-client#75]
Last run ~2012. Seemed to be having problems:

NYT bestseller bot is adding, then immediately replacing, tags:

http://openlibrary.org/works/OL16010721W/Lost_in_Shangri-la?m=history

more: http://openlibrary.org/people/nyt_bestsellers_bot

see: https://github.com/internetarchive/openlibrary/issues/54

**Comment by hornc** [comment]
@mekarpeles can we close this now the NYT bot has new life over at https://github.com/internetarchive/openlibrary-bots/tree/master/NY-Times-Bestseller-Bot ?
Perhaps raise any outstanding issues on that repo?
