### ISSUE TITLE
Remove deleted author records from Solr index

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary-client#78]
Attached are lists of 101851 deleted author IDs and 270619 redirected author IDs from the 2018-03-31 dump.

The deleted authors should be removed from the index. The directed ones, we probably still want to be able to look up by ID, but we should make sure that they're not indexed as a target anywhere (perhaps a task for a separate ticket?).

[deleted-author-ids.txt](https://github.com/internetarchive/openlibrary-client/files/1893047/deleted-author-ids.txt)
[redirect-author-ids.txt](https://github.com/internetarchive/openlibrary-client/files/1893050/redirect-author-ids.txt)

**Comment by hornc** [comment]
Thanks @tfmorris , sorry for not getting to these sooner! I've had a break from Solr, but am getting back into it again. I'll check out that status of the various items and see about automating (or fixing!) what is needed to bring the index up to date.

**Comment by tfmorris** [comment]
https://github.com/internetarchive/openlibrary/issues/1445 describes the redirect portion of this issue from a user point of view and https://github.com/internetarchive/openlibrary/issues/2552 proposes a fix.

The deleted records need to be addressed as well, but the lists here are stale and this is better suited for the main OpenLibrary repo, so closing.
