### ISSUE TITLE
Delete works & editions with bogus "Dumpbin" titles

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary-client#79]
A dumpbin is a Wholesale-to-Retail package for convenient handling of one, two, or three dozen copies in the bookstore. In several hundred cases from 2008 or 2009 we imported Amazon records (since 404ed) that treated dumpbins as books. These should all be made to vanish:
https://openlibrary.org/search?q=title%3A+%22dumpbin%22

**Comment by LeadSongDog** [comment]
Also for the "[nn] copy bin":
 https://openlibrary.org/search?q=title%3A+"copy+bin"
and the "[nn] copy display":
https://openlibrary.org/search?q=title%3A+"Copy+Display"

**Comment by LeadSongDog** [comment]
@mekarpeles please tag as datacleanup

**Comment by LeadSongDog** [comment]
Other title keywords to look for:
Unit, Pack, Calendar, Flat, Box, Set
Not all will be simple, but they should draw closer examination, particularly if the only ID is a distributor's and no library holds it.

**Comment by hornc** [comment]
closing in favour of the main OL issue
