### ISSUE TITLE
complex networks and text mining analytics

### ISSUE THREAD

**Issue by ttm** [internetarchive/openlibrary-client#8]
It seems to me that an interface for further data analytics would enhance
our experience with Archive.org.
I can tackle this by using complex networks and text mining techniques,
because I have developed research on these topics.
Immediate ideas are:
*) Derive network by users interactions and vocabulary usage and deliver some graphical interfaces for exploring these structures.
*) Counting of words, tags, terms and user activity.

I understand it might be late for coping with GSoC, but if you find it suitable,
I might apply.
My apologies for not making this contact earlier, but I handed my doctorate
dissertation a few days ago and could not concentrate as needed until now.
Some info about my research and software development efforts are gathered here:
https://pastebin.com/iNNuN4fy7
Anyway, this topic might be of use for the Archive.org community as a whole and for
developments outside GSoC, but I did not find where to post this.

Best Regards!
Renato Fabbri

**Comment by mekarpeles** [comment]
@ttm you may be interested in @jjjake's project: https://github.com/jjjake/internetarchive and https://github.com/jjjake/iamine (the official Internet Archive command line tool and Internet Archive data-mining toolkit). Jake leads these projects at the Internet Archive.

This specific repository is for the Open Library client (for accessing data from Open Library)

cc: @markjgraham who is leading Internet Archive efforts around GSoC
