### ISSUE TITLE
Book added by CLI doesn't seem to be searchable by title

### ISSUE THREAD

**Issue by adamreis** [internetarchive/openlibrary-client#97]
I added [this book](https://openlibrary.org/books/OL26468254M/All_We_Ever_Wanted_A_Novel) via the CLI, but can't find it by searching for `All We Ever Wanted: A Novel` -- only by searching for its OLID.

**Comment by adamreis** [comment]
The command I used to add the book:

```
python3 -m olclient.cli --create "{\"title\":\"All We Ever Wanted: A Novel\", \"author\": \"Emily Giffin\", \"identifiers\":{\"isbn_10\": \"0399178929\"}}"
```

**Comment by hornc** [comment]
@adamreis I think this might be due to the ~15 min delay for items to be added into the solr index
.

Are these your books?
https://openlibrary.org/search?q=All+We+Ever+Wanted%3A+A+Novel&mode=everything

**Comment by hornc** [comment]
I believe this is no longer a current issue?
