### ISSUE TITLE
Book added by CLI seems to not have picked up ISBN 10

### ISSUE THREAD

**Issue by adamreis** [internetarchive/openlibrary-client#98]
I added a book with the following command:

```
python3 -m olclient.cli --create "{\"title\":\"All We Ever Wanted: A Novel\", \"author\": \"Emily Giffin\", \"identifiers\":{\"isbn_10\": \"0399178929\"}}"
```

It succeeded, but the [resulting book page](https://openlibrary.org/books/OL26468254M/All_We_Ever_Wanted_A_Novel) doesn't have the ISBN number:

<img width="604" alt="screenshot 2018-07-07 14 31 35" src="https://user-images.githubusercontent.com/2453460/42414798-7d1f95d8-81f2-11e8-8888-dfb992e929f0.png">

**Comment by hornc** [comment]
Hi @adamreis, thanks for trying ol-client, I just had a look at your command and the result; for the command line json `isbn_10` takes a list of isbns rather than a string.
We should add validation so it catches and warns if it gets an incorrect type
